package rugse.team2.MeetGroningen.Activities;

import android.Manifest;
import android.content.Intent;
import android.content.IntentSender;
import android.content.pm.PackageManager;
import android.database.sqlite.SQLiteDatabase;
import android.location.Location;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.support.v4.app.FragmentActivity;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ListView;
import android.widget.Toast;

import com.google.android.gms.common.ConnectionResult;
import com.google.android.gms.common.api.GoogleApiClient;
import com.google.android.gms.location.LocationListener;
import com.google.android.gms.location.LocationRequest;
import com.google.android.gms.location.LocationServices;
import com.google.android.gms.maps.CameraUpdate;
import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.model.BitmapDescriptorFactory;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.LatLngBounds;
import com.google.android.gms.maps.model.Marker;
import com.google.android.gms.maps.model.MarkerOptions;
import rugse.team2.MeetGroningen.Constants;
import rugse.team2.MeetGroningen.DatabaseStuff.DatabaseHelper;
import rugse.team2.MeetGroningen.Objects.Landmark;
import rugse.team2.MeetGroningen.Objects.Quest;
import rugse.team2.MeetGroningen.Objects.User;

import java.util.ArrayList;
import java.util.List;

/**
 * This class represents the activity (Android window) for previewing a quest.
 * It gets the landmarks corresponding to a certain quest from the database and
 * displays them as markers in a map, together with one's own current location,
 * and shows their names in an ordered list too to provide a complete overview.
 */
public class QuestPreviewActivity extends FragmentActivity implements
        GoogleApiClient.ConnectionCallbacks,
        GoogleApiClient.OnConnectionFailedListener,
        LocationListener,
        OnMapReadyCallback {

    /** A tag attached to logging messages generated by this class, which equals the class's name. */
    public static final String TAG = QuestPreviewActivity.class.getSimpleName();
    /** A request code to send to Google Play Services when attempting to resolve connection errors, which is again returned in Activity.onActivityResult. */
    private final static int CONNECTION_FAILURE_RESOLUTION_REQUEST = 9000;

    /** The (Google) map. */
    private GoogleMap mMap; //might be null if the Google Play Services APK is not available

    /** The main entry point for Google Play Services integration. */
    private GoogleApiClient mGoogleApiClient;
    /** The instance used for requesting one's location via Google Play Services. */
    private LocationRequest mLocationRequest;
    /** The list of markers of landmark locations. */
    private List<Marker> markers;

    /** The quest to be previewed, passed by the previous activity. */
    private Quest passedQuest;
    /** The current application user. */
    private User currentUser;

    /** The helper instance for exchanging information with the application's SQLite database. */
    private DatabaseHelper dbhelper;
    /** The button for adding the previewed quest to the current user's list of started quests. */
    private Button pickQuest;
    /** The button for directly going on the quest that has just been picked. */
    private Button startQuest;

    /**
     * Initialises the activity as described above, and binds clicking 'pick' to adding the previewed
     * quest to the current user in the database and 'start' to starting a new OnQuestActivity.
     * Also makes clicking a landmark from the list move the map camera to focus on it.
     *
     * @param savedInstanceState If the activity is being re-initialised after previously being shut down, then this Bundle
     *                           contains the data it most recently supplied in onSaveInstanceState(Bundle). Otherwise it is null.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);

        passedQuest = (Quest) getIntent().getSerializableExtra("PassedQuest");
        //get the database and get the user from it
        dbhelper = new DatabaseHelper(this);
        SQLiteDatabase db = dbhelper.getReadableDatabase();
        currentUser = dbhelper.getUser(db);

        setContentView(rugse.team2.MeetGroningen.R.layout.activity_questpreview);

        SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(rugse.team2.MeetGroningen.R.id.map);
        mapFragment.getMapAsync(this);

        mGoogleApiClient = new GoogleApiClient.Builder(this)
                .addConnectionCallbacks(this)
                .addOnConnectionFailedListener(this)
                .addApi(LocationServices.API)
                .build();

        //create the LocationRequest object
        mLocationRequest = LocationRequest.create()
                .setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
                .setInterval(10 * Constants.MILLISEC) //10 seconds, in milliseconds
                .setFastestInterval(Constants.MILLISEC); //1 second, in milliseconds

        ListView listView = (ListView) findViewById(rugse.team2.MeetGroningen.R.id.listView2);
        ArrayAdapter<Landmark> adapter = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1, passedQuest.getLandmarks());
        listView.setAdapter(adapter);

        //redirect to quest content page, passing the chosen quest
        listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Landmark selectedlm = (Landmark) parent.getAdapter().getItem(position);
                mMap.moveCamera(CameraUpdateFactory.newLatLng(selectedlm.getLocation()));


            }
        });

        pickQuest = (Button) findViewById(rugse.team2.MeetGroningen.R.id.addButton_questPreview);
        startQuest = (Button) findViewById(rugse.team2.MeetGroningen.R.id.startButton_questPreview);

        pickQuest.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                currentUser.addQuest(passedQuest);
                dbhelper.updateInDatabase(dbhelper, currentUser);
                pickQuest.setVisibility(View.GONE);
                Toast.makeText(getApplicationContext(),
                        rugse.team2.MeetGroningen.R.string.questAdded, Toast.LENGTH_LONG).show();
                startQuest.setVisibility(View.VISIBLE);
            }
        });

        startQuest.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                currentUser.setActiveQuest(passedQuest);
                dbhelper.updateInDatabase(dbhelper, currentUser);
                Intent i = new Intent(getBaseContext(), OnQuestActivity.class);
                i.putExtra("PassedQuest", passedQuest);
                startActivity(i);
            }
        });

    }

    /** Resumes the activity after having been paused, reconnecting to Google Play Services, and then hiding the
      * 'pick' button if it had been clicked already and hence was removed in favour of the 'start' button. */
    @Override
    protected void onResume() {
        super.onResume();
        mGoogleApiClient.connect();

        //check if quest is already in User's quests and change accordingly to (don't) show pick quest button
        currentUser = dbhelper.getUser(dbhelper.getReadableDatabase());
        for(Quest q : currentUser.getCurrentQuests()) {
            if (q.getID().equals(passedQuest.getID())) {
                Log.d("TEST", "passedQuest is in currentUser, onResume()");
                //pickQuest.setVisibility(View.GONE); //remove the 'pick this quest' button
            }
        }
    }

    /** Pauses the activity, disconnecting from Google Play Services until the activity is resumed. */
    @Override
    protected void onPause() {
        super.onPause();

        if (mGoogleApiClient.isConnected()) {
            LocationServices.FusedLocationApi.removeLocationUpdates(mGoogleApiClient, this);
            mGoogleApiClient.disconnect();
        }
    }

    /**
     * Saves the map for further use. This is called automatically after the map has been prepared
     * and is ready for use. Also adds all landmarks within the passed quest to the map as markers.
     *
     * @param map The (Google) map which has been prepared asynchronously and is now ready for use.
     */
    @Override
    public void onMapReady(GoogleMap map) {
       //get the locations of the landmarks in this quest
        mMap = map;
        Marker testmark;
        markers = new ArrayList<>();
        for (Landmark landmark : passedQuest.getLandmarks()) {
            testmark = mMap.addMarker(new MarkerOptions()
                    .position(landmark.getLocation())
                    .title(landmark.getName()));
            markers.add(testmark);
        }
     }


    /**
     * Handles one's updated location by moving their location marker on the map, and by moving
     * the map camera to keep the user and all landmarks within the previewed quest in view.
     *
     * @param location The new location.
     */
    private void handleNewLocation(Location location) {
        Log.d(TAG, location.toString());

        double currentLatitude = location.getLatitude();
        double currentLongitude = location.getLongitude();

        LatLng latLng = new LatLng(currentLatitude, currentLongitude);

        MarkerOptions options = new MarkerOptions()
                .position(latLng)
                .title("I am here!")
                .icon(BitmapDescriptorFactory.fromResource(rugse.team2.MeetGroningen.R.mipmap.icon2)) ;
        mMap.addMarker(options);
        mMap.setMyLocationEnabled(true);
        //loop through the landmark locations to make sure they are all displayed in the map
        LatLngBounds.Builder builder = new LatLngBounds.Builder();
        for (Marker marker : markers) {
            builder.include(marker.getPosition());
        }
        builder.include(options.getPosition());
        LatLngBounds bounds = builder.build();
        CameraUpdate cu = CameraUpdateFactory.newLatLngBounds(bounds, Constants.PADDING);
        mMap.animateCamera(cu);
    }

    /**
     * This method is called automatically when the application has connected successfully to Google Play Services.
     * Checks if GPS is enabled, finds one's current location if possible, and calls handleNewLocation to handle it.
     *
     * @param bundle Bundle of data provided to clients by Google Play Services. May be null if no content is provided by the service.
     */
    @Override
    public void onConnected(Bundle bundle) {
        if (ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            // TODO: Consider calling
            //    ActivityCompat#requestPermissions
            // here to request the missing permissions, and then overriding
            //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
            //                                          int[] grantResults)
            // to handle the case where the user grants the permission. See the documentation
            // for ActivityCompat#requestPermissions for more details.
            return;
        }
        Location location = LocationServices.FusedLocationApi.getLastLocation(mGoogleApiClient);
        if (location == null) {
            LocationServices.FusedLocationApi.requestLocationUpdates(mGoogleApiClient, mLocationRequest, this);
        }
        else {
            handleNewLocation(location);
        }
    }

    /**
     * Empty method that makes sure that nothing is done when the connection to Google Play Services is suspended.
     *
     * @param i The cause of the suspension, to be specific a value of 1 for deliberate
     *          disconnection, and a value of 2 for unintentional network loss.
     */
    @Override
    public void onConnectionSuspended(int i) {

    }

    /**
     * This method is called when connecting to Google Play Services failed.
     * It tries resolving the error encountered while connecting to Google
     * Play Services automatically, and logs an error message if this fails.
     *
     * @param connectionResult A ConnectionResult object that can be used for deciding what kind of error occurred, and for resolving it.
     */
    @Override
    public void onConnectionFailed(ConnectionResult connectionResult) {
        /*
         * Google Play Services can resolve some errors it detects. If
         * the error has a resolution, try sending an Intent to start
         * a Google Play Services activity that can resolve the error.
         */
        if (connectionResult.hasResolution()) {
            try {
                //start an Activity that tries to resolve the error
                connectionResult.startResolutionForResult(this, CONNECTION_FAILURE_RESOLUTION_REQUEST);
                /*
                 * Thrown if Google Play Services cancelled the original PendingIntent.
                 */
            } catch (IntentSender.SendIntentException e) {
                //log the error
                e.printStackTrace();
            }
        } else {
            /*
             * If no resolution is available, log the error.
             */
            Log.i(TAG, "Location services connection failed with code " + connectionResult.getErrorCode());
        }
    }

    /**
     * Is called automatically whenever the current user's location changes,
     * itself calling handleNewLocation to actually handle the updated location.
     *
     * @param location The new location.
     */
    @Override
    public void onLocationChanged(Location location) {
        handleNewLocation(location);
    }
}
